name: Deploy

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: ghcr.io/apulatjonov/mytestapp
      TAG: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u apulatjonov --password-stdin

      - name: Build Image
        run: docker build --pull -t $IMAGE_NAME:$TAG .

      - name: Push Image
        run: docker push $IMAGE_NAME:$TAG

      - name: Deploy With Full Protection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            set -e
            
            if [ "${{ github.ref_name }}" = "main" ]; then
              NS="prod"
            else
              NS="dev"
            fi

            IMAGE="ghcr.io/apulatjonov/mytestapp:${{ github.sha }}"
            URL="http://95.182.118.251.nip.io"
            
            echo "Deploying to namespace: $NS"

            sudo kubectl set image deployment/test test=$IMAGE -n $NS

            if ! sudo kubectl rollout status deployment/test -n $NS --timeout=120s; then
              sudo kubectl rollout undo deployment/test -n $NS
              exit 1
            fi

            if ! curl -f $URL/api/ping; then
              echo "Ping failed -> rollback"
              sudo kubectl rollout undo deployment/test -n $NS
              exit 1
            fi

            if ! curl -f $URL/actuator/health; then
              echo "Health failed -> rollback"
              sudo kubectl rollout undo deployment/test -n $NS
              exit 1
            fi

            echo "Deployment fully successful"