name: Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: ghcr.io/apulatjonov/mytestapp
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin

      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u apulatjonov --password-stdin

      - name: Build Docker Image
        run: docker build --pull -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker Image
        run: docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            sudo kubectl set image deployment/test test=$IMAGE_NAME:$IMAGE_TAG -n dev
            sudo kubectl rollout status deployment/test -n dev --timeout=180s
            sudo kubectl get pods -n dev