name: Deploy Dev

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: ghcr.io/apulatjonov/mytestapp
      TAG: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u apulatjonov --password-stdin

      - name: Build Image
        run: docker build -t $IMAGE_NAME:$TAG .

      - name: Push Image
        run: docker push $IMAGE_NAME:$TAG

      - name: Inject image tag
        run: |
          sed -i "s|IMAGE_PLACEHOLDER|$IMAGE_NAME:$TAG|g" k8s/dev/deployment.yaml

      - name: Deploy manifests
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            mkdir -p /opt/apps/mytestapp

      - name: Copy manifests
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "k8s/dev/*"
          target: "/opt/apps/mytestapp"

      - name: Apply manifests
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            kubectl apply -f /opt/apps/mytestapp/k8s/dev/
            kubectl rollout status deployment/test -n dev --timeout=120s