name: Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: ghcr.io/apulatjonov/mytestapp
      TAG: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u apulatjonov --password-stdin

      - name: Build Image
        run: docker build --pull -t $IMAGE_NAME:$TAG .

      - name: Push Image
        run: docker push $IMAGE_NAME:$TAG

      - name: Deploy With Rollback Protection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            set -e

            echo "Deploying $IMAGE_NAME:$TAG"

            sudo kubectl set image deployment/test test=$IMAGE_NAME:$TAG -n dev

            if sudo kubectl rollout status deployment/test -n dev --timeout=120s; then
              echo "Deployment successful"
            else
              echo "Deployment failed. Rolling back..."
              sudo kubectl rollout undo deployment/test -n dev
              sudo kubectl rollout status deployment/test -n dev --timeout=120s
              exit 1
            fi